### ISSUE TITLE
crackme 的frida方式

### ISSUE THREAD

**Issue by ylww** [lulululbj/android-reverse#1]
`Java.perform(function() {
  var string = Java.use("java.lang.String");
  string.equalsIgnoreCase.implementation = function(var1) {
    send("hook equalsIgnoreCase 方法");
    send("真正的密码为：" + this.toString());
    return this.equalsIgnoreCase(var1);
  };
});
`

注册码需要满16位
![image](https://user-images.githubusercontent.com/4017167/58372114-b657e880-7f4b-11e9-83b9-e168940b5ca4.png)
![image](https://user-images.githubusercontent.com/4017167/58372115-bbb53300-7f4b-11e9-8f3a-bd334993f99f.png)

**Comment by lulululbj** [comment]
恩，在校验注册码之前，会先判断输入的注册码是否是 16 位

**Comment by lulululbj** [comment]
恩，在校验注册码之前，会先判断输入的注册码是否是 16 位
